name: Integration Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        node-version: [16.x, 18.x, 19.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: nodejs-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run Test
        run: yarn test
        env:
          API_BASE: ${{ secrets.API_BASE }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          SMARTPAY_API_PREFIX: ${{ secrets.SMARTPAY_API_PREFIX }}
